In [191]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn import preprocessing

In [192]:
df = pd.read_csv('train.csv', encoding='iso-8859-1')
df = pd.get_dummies(data=df, columns=['InterviewerId', 'Interviewee'])

In [193]:
tfv = TfidfVectorizer(min_df=0.01, max_features=None, 
            strip_accents='unicode', analyzer='word',token_pattern=r'\w{1,}',
            ngram_range=(1, 3), use_idf=1,smooth_idf=1,sublinear_tf=1,
            stop_words = 'english')


df_tfv = tfv.fit_transform(df['Desc_B'])
df1 = pd.DataFrame(df_tfv.toarray(), columns=tfv.get_feature_names())
df.drop('Desc_A', axis=1, inplace=True)
df.drop('Desc_B', axis=1, inplace=True)
df = pd.concat([df, df1], axis=1)
print(res)
y = df['Hire_call_interviewer_1']
x = df.drop(['Hire_call_interviewer_1'], axis=1)

xtrain, xvalid, ytrain, yvalid = train_test_split(x, y, 
                                                  stratify=y, 
                                                  random_state=42, 
                                                  test_size=0.2, shuffle=True)

   Score_A_Interviewer_1  Score_B  \
0                      6        5
1                      7        5
2                      8        7
3                      7        5
4                      4        5
5                      4        7

                                              Desc_B  Prio_A  Prio_B  \
0  Â Talks less. Finds it a bit difficult to commu...      10       6
1  He said he is working on some ML algo to class...      10       6
2                                               Good      10       6
3  He talked about seller recall product he worke...      10       6
4                                  Doesn't talk much      10       6
5                                           was fine      10       6

   Years of exp  Hire_call_interviewer_1  InterviewerId_Prasanth Menon  \
0             5                        0                             0
1             4                        1                             0
2             4                        1                             1
3             4                        1                             0
4             6                        0                             0
5             7                        0                             0

   InterviewerId_Prashant Menon  InterviewerId_Rahul Kumar  \
0                             1                          0
1                             0                          1
2                             0                          0
3                             0                          0
4                             0                          0
5                             0                          1

            ...            worked didn t     write  write code  \
0           ...                 0.065664  0.000000    0.000000
1           ...                 0.000000  0.000000    0.000000
2           ...                 0.000000  0.000000    0.000000
3           ...                 0.000000  0.079526    0.079526
4           ...                      NaN       NaN         NaN
5           ...                      NaN       NaN         NaN

   write code good     wrong  wrong way  wrong way initially      year  \
0         0.000000  0.065664   0.065664             0.065664  0.065664
1         0.000000  0.000000   0.000000             0.000000  0.000000
2         0.000000  0.000000   0.000000             0.000000  0.000000
3         0.079526  0.000000   0.000000             0.000000  0.000000
4              NaN       NaN        NaN                  NaN       NaN
5              NaN       NaN        NaN                  NaN       NaN

   year candidate  year candidate overall
0        0.065664                0.065664
1        0.000000                0.000000
2        0.000000                0.000000
3        0.000000                0.000000
4             NaN                     NaN
5             NaN                     NaN

[6 rows x 539 columns]

In [194]:
xtrain

,Score_A_Interviewer_1,Score_B,Prio_A,Prio_B,Years of exp,InterviewerId_Prasanth Menon,InterviewerId_Prashant Menon,InterviewerId_Rahul Kumar,InterviewerId_Rishab,InterviewerId_Shyam,...,work,worked,worked flipkart,worked flipkart able,working,working ml,working ml algo,wrong,wrong couldn,wrong couldn t
4,4,5,10,6,6,0,0,0,0,1,...,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.000000
3,7,5,10,6,4,0,0,0,1,0,...,0.0,0.115146,0.115146,0.115146,0.0,0.0,0.0,0.115146,0.115146,0.115146
0,6,5,10,6,5,0,1,0,0,0,...,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.000000
2,8,7,10,6,4,1,0,0,0,0,...,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.000000

In [195]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

clf = RandomForestClassifier()
clf.fit(xtrain, ytrain)

pred = clf.predict(xvalid)
print(accuracy_score(yvalid, pred))

0.5